environment.name=prod
spring.datasource.username=irenebouslama
spring.datasource.password=456cerise
spring.datasource.url=jdbc:mysql://localhost:3306/hello_neighbors_spring_db?createDatabaseIfNotExist=true&serverTimezone=UTC
front.url=http://localhost:4200